#!/usr/bin/env bash
# Installing nginx
#^ start of line
# \t is tab

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
search_str="\tlocation / {"
replace_str="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$search_str@$replace_str@" /etc/nginx/sites-available/default
sudo service nginx restart
