#!/usr/bin/env bash
# Installing nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx restart
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
file=/etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" "$file"
sed -i "/listen 80 default_server/a error_page 404 /404.html;" "$file"
service nginx restart;
