#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it
archive=$(date +"%d-%m-%y")
mysql -u root -p --all-databases > backup.sql
$1
sudo tar -cvzf "$mydate".tar.gz backup.sql
